### ISSUE TITLE
joomla 5 compatability

### ISSUE THREAD

**Issue by raramuridesign** [jreviews/plg_loginwithemail#2]
Hi Team
Does this work on J5... 
M.

**Comment by jreviews** [comment]
@raramuridesign The code is very straightforward and I don't see any reason why it wouldn't be compatible. Take it for a spin and let us know.

**Comment by raramuridesign** [comment]
I can confirm its working @jreviews 

I had one question though. Would it be possible to force the user to use email rather than username ?
M
